default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-moviechanpuru_development

test:
  <<: *default
  database: rails-moviechanpuru_test
